[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=0.6.3",
    "langchain>=0.3.21",
    "openai>=1.68.2",
    "requests>=2.32.3",
    "rich>=13.9.4",
]
